const kennzeichenDaten = [
    { kennzeichen: "A", stadt: "Augsburg", bundesland: "Bayern" },
    { kennzeichen: "AA", stadt: "Aalen", bundesland: "Baden-Württemberg" },
    { kennzeichen: "AB", stadt: "Aschaffenburg", bundesland: "Bayern" },
    { kennzeichen: "ABG", stadt: "Altenburger Land", bundesland: "Thüringen" },
    { kennzeichen: "ABI", stadt: "Anhalt-Bitterfeld", bundesland: "Sachsen-Anhalt" },
    { kennzeichen: "AC", stadt: "Aachen", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "AE", stadt: "Auerbach", bundesland: "Sachsen" },
    { kennzeichen: "AH", stadt: "Ahaus", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "AIB", stadt: "Bad Aibling", bundesland: "Bayern" },
    { kennzeichen: "AIC", stadt: "Aichach-Friedberg", bundesland: "Bayern" },
    { kennzeichen: "AK", stadt: "Altenkirchen", bundesland: "Rheinland-Pfalz" },
    { kennzeichen: "AL", stadt: "Altena", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "ALF", stadt: "Alfeld (Leine)", bundesland: "Niedersachsen" },
    { kennzeichen: "ALS", stadt: "Alsfeld", bundesland: "Hessen" },
    { kennzeichen: "ALZ", stadt: "Alzenau", bundesland: "Bayern" },
    { kennzeichen: "AM", stadt: "Amberg", bundesland: "Bayern" },
    { kennzeichen: "AN", stadt: "Ansbach", bundesland: "Bayern" },
    { kennzeichen: "ANA", stadt: "Annaberg", bundesland: "Sachsen" },
    { kennzeichen: "ANG", stadt: "Angermünde", bundesland: "Brandenburg" },
    { kennzeichen: "ANK", stadt: "Anklam", bundesland: "Mecklenburg-Vorpommern" },
    { kennzeichen: "AÖ", stadt: "Altötting", bundesland: "Bayern" },
    { kennzeichen: "AP", stadt: "Weimarer Land (Apolda)", bundesland: "Thüringen" },
    { kennzeichen: "APD", stadt: "Apolda", bundesland: "Thüringen" },
    { kennzeichen: "AR", stadt: "Arnsberg", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "ARN", stadt: "Arnstadt", bundesland: "Thüringen" },
    { kennzeichen: "ART", stadt: "Artern", bundesland: "Thüringen" },
    { kennzeichen: "ASD", stadt: "Aschendorf-Hümmling", bundesland: "Niedersachsen" },
    { kennzeichen: "AS", stadt: "Amberg-Sulzbach", bundesland: "Bayern" },
    { kennzeichen: "ASL", stadt: "Aschersleben-Staßfurt", bundesland: "Sachsen-Anhalt" },
    { kennzeichen: "ASZ", stadt: "Aue-Schwarzenberg", bundesland: "Sachsen" },
    { kennzeichen: "AT", stadt: "Altentreptow", bundesland: "Mecklenburg-Vorpommern" },
    { kennzeichen: "AU", stadt: "Aue", bundesland: "Sachsen" },
    { kennzeichen: "AUR", stadt: "Aurich", bundesland: "Niedersachsen" },
    { kennzeichen: "AW", stadt: "Ahrweiler", bundesland: "Rheinland-Pfalz" },
    { kennzeichen: "AZ", stadt: "Alzey-Worms", bundesland: "Rheinland-Pfalz" },
    { kennzeichen: "AZE", stadt: "Anhalt-Zerbst", bundesland: "Sachsen-Anhalt" },
    { kennzeichen: "B", stadt: "Berlin", bundesland: "Berlin" },
    { kennzeichen: "BA", stadt: "Bamberg", bundesland: "Bayern" },
    { kennzeichen: "BAD", stadt: "Baden-Baden", bundesland: "Baden-Württemberg" },
    { kennzeichen: "BAR", stadt: "Barnim", bundesland: "Brandenburg" },
    { kennzeichen: "BB", stadt: "Böblingen", bundesland: "Baden-Württemberg" },
    { kennzeichen: "BBG", stadt: "Bernburg", bundesland: "Sachsen-Anhalt" },
    { kennzeichen: "BC", stadt: "Biberach", bundesland: "Baden-Württemberg" },
    { kennzeichen: "BCH", stadt: "Buchen (Odenwald)", bundesland: "Baden-Württemberg" },
    { kennzeichen: "BE", stadt: "Beckum", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "BED", stadt: "Brand-Erbisdorf", bundesland: "Sachsen" },
    { kennzeichen: "BEI", stadt: "Beilngries", bundesland: "Bayern" },
    { kennzeichen: "BEL", stadt: "Belzig", bundesland: "Brandenburg" },
    { kennzeichen: "BER", stadt: "Bernau", bundesland: "Brandenburg" },
    { kennzeichen: "BF", stadt: "Burgsteinfurt", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "BGD", stadt: "Berchtesgaden", bundesland: "Bayern" },
    { kennzeichen: "BGL", stadt: "Berchtesgadener Land", bundesland: "Bayern" },
    { kennzeichen: "BH", stadt: "Bühl", bundesland: "Baden-Württemberg" },
    { kennzeichen: "BI", stadt: "Bielefeld", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "BID", stadt: "Biedenkopf", bundesland: "Hessen" },
    { kennzeichen: "BIN", stadt: "Bingen am Rhein", bundesland: "Rheinland-Pfalz" },
    { kennzeichen: "BIR", stadt: "Birkenfeld", bundesland: "Rheinland-Pfalz" },
    { kennzeichen: "BIT", stadt: "Bitburg-Prüm (Eifelkreis)", bundesland: "Rheinland-Pfalz" },
    { kennzeichen: "BIW", stadt: "Bischofswerda", bundesland: "Sachsen" },
    { kennzeichen: "BK", stadt: "Backnang", bundesland: "Baden-Württemberg" },
    { kennzeichen: "BK", stadt: "Landkreis Börde", bundesland: "Sachsen-Anhalt" },
    { kennzeichen: "BKS", stadt: "Bernkastel-Kues", bundesland: "Rheinland-Pfalz" },
    { kennzeichen: "BL", stadt: "Zollernalbkreis (Balingen)", bundesland: "Baden-Württemberg" },
    { kennzeichen: "BLB", stadt: "Berleburg", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "BLK", stadt: "Burgenlandkreis", bundesland: "Sachsen-Anhalt" },
    { kennzeichen: "BM", stadt: "Rhein-Erft-Kreis (Bergheim)", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "BN", stadt: "Bonn", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "BNA", stadt: "Borna", bundesland: "Sachsen" },
    { kennzeichen: "BO", stadt: "Bochum", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "BÖ", stadt: "Bördekreis", bundesland: "Sachsen-Anhalt" },
    { kennzeichen: "BOG", stadt: "Bogen", bundesland: "Bayern" },
    { kennzeichen: "BOH", stadt: "Bocholt", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "BOR", stadt: "Borken", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "BOT", stadt: "Bottrop", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "BR", stadt: "Bruchsal", bundesland: "Baden-Württemberg" },
    { kennzeichen: "BRA", stadt: "Wesermarsch (Brake)", bundesland: "Niedersachsen" },
    { kennzeichen: "BRB", stadt: "Brandenburg", bundesland: "Brandenburg" },
    { kennzeichen: "BRG", stadt: "Burg", bundesland: "Sachsen-Anhalt" },
    { kennzeichen: "BRI", stadt: "Brilon", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "BRK", stadt: "Bad Brückenau", bundesland: "Bayern" },
    { kennzeichen: "BRL", stadt: "Blankenburg (Braunlage)", bundesland: "Niedersachsen" },
    { kennzeichen: "BRV", stadt: "Bremervörde", bundesland: "Niedersachsen" },
    { kennzeichen: "BS", stadt: "Braunschweig", bundesland: "Niedersachsen" },
    { kennzeichen: "BSB", stadt: "Bersenbrück", bundesland: "Niedersachsen" },
    { kennzeichen: "BSK", stadt: "Beeskow", bundesland: "Brandenburg" },
    { kennzeichen: "BT", stadt: "Bayreuth", bundesland: "Bayern" },
    { kennzeichen: "BTF", stadt: "Bitterfeld", bundesland: "Sachsen-Anhalt" },
    { kennzeichen: "BU", stadt: "Burgdorf", bundesland: "Niedersachsen" },
    { kennzeichen: "BÜD", stadt: "Büdingen", bundesland: "Hessen" },
    { kennzeichen: "BÜR", stadt: "Büren", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "BÜS", stadt: "Büsingen (Konstanz)", bundesland: "Baden-Württemberg" },
    { kennzeichen: "BÜZ", stadt: "Bützow", bundesland: "Mecklenburg-Vorpommern" },
    { kennzeichen: "BUL", stadt: "Burglengenfeld", bundesland: "Bayern" },
    { kennzeichen: "BZ", stadt: "Bautzen", bundesland: "Sachsen" },
    { kennzeichen: "BZA", stadt: "Bergzabern", bundesland: "Rheinland-Pfalz" },
    { kennzeichen: "C", stadt: "Chemnitz", bundesland: "Sachsen" },
    { kennzeichen: "CA", stadt: "Calau", bundesland: "Brandenburg" },
    { kennzeichen: "CAS", stadt: "Castrop-Rauxel", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "CB", stadt: "Cottbus", bundesland: "Brandenburg" },
    { kennzeichen: "CE", stadt: "Celle", bundesland: "Niedersachsen" },
    { kennzeichen: "CHA", stadt: "Cham", bundesland: "Bayern" },
    { kennzeichen: "CLP", stadt: "Cloppenburg", bundesland: "Niedersachsen" },
    { kennzeichen: "CLZ", stadt: "Clausthal-Zellerfeld", bundesland: "Niedersachsen" },
    { kennzeichen: "CO", stadt: "Coburg", bundesland: "Bayern" },
    { kennzeichen: "COC", stadt: "Cochem-Zell", bundesland: "Rheinland-Pfalz" },
    { kennzeichen: "COE", stadt: "Coesfeld", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "CR", stadt: "Crailsheim", bundesland: "Baden-Württemberg" },
    { kennzeichen: "CUX", stadt: "Cuxhaven", bundesland: "Niedersachsen" },
    { kennzeichen: "CW", stadt: "Calw", bundesland: "Baden-Württemberg" },
    { kennzeichen: "D", stadt: "Düsseldorf", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "DA", stadt: "Darmstadt", bundesland: "Hessen" },
    { kennzeichen: "DAH", stadt: "Dachau", bundesland: "Bayern" },
    { kennzeichen: "DAN", stadt: "Lüchow-Dannenberg", bundesland: "Niedersachsen" },
    { kennzeichen: "DAU", stadt: "Daun", bundesland: "Rheinland-Pfalz" },
    { kennzeichen: "DBR", stadt: "Bad Doberan", bundesland: "Mecklenburg-Vorpommern" },
    { kennzeichen: "DD", stadt: "Dresden", bundesland: "Sachsen" },
    { kennzeichen: "DE", stadt: "Dessau-Roßlau", bundesland: "Sachsen-Anhalt" },
    { kennzeichen: "DEG", stadt: "Deggendorf", bundesland: "Bayern" },
    { kennzeichen: "DEL", stadt: "Delmenhorst", bundesland: "Niedersachsen" },
    { kennzeichen: "DGF", stadt: "Dingolfing-Landau", bundesland: "Bayern" },
    { kennzeichen: "DH", stadt: "Diepholz", bundesland: "Niedersachsen" },
    { kennzeichen: "DI", stadt: "Dieburg", bundesland: "Hessen" },
    { kennzeichen: "DIL", stadt: "Dillkreis (Dillenburg)", bundesland: "Hessen" },
    { kennzeichen: "DIN", stadt: "Dinslaken", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "DIZ", stadt: "Diez", bundesland: "Rheinland-Pfalz" },
    { kennzeichen: "DKB", stadt: "Dinkelsbühl", bundesland: "Bayern" },
    { kennzeichen: "DL", stadt: "Döbeln", bundesland: "Sachsen" },
    { kennzeichen: "DLG", stadt: "Dillingen a.d. Donau", bundesland: "Bayern" },
    { kennzeichen: "DM", stadt: "Demmin", bundesland: "Mecklenburg-Vorpommern" },
    { kennzeichen: "DN", stadt: "Düren", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "DO", stadt: "Dortmund", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "DON", stadt: "Donau-Ries (Donauwörth)", bundesland: "Bayern" },
    { kennzeichen: "DS", stadt: "Donaueschingen", bundesland: "Baden-Württemberg" },
    { kennzeichen: "DT", stadt: "Lippe (Detmold)", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "DU", stadt: "Duisburg", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "DUD", stadt: "Duderstadt", bundesland: "Niedersachsen" },
    { kennzeichen: "DÜW", stadt: "Bad Dürkheim", bundesland: "Rheinland-Pfalz" },
    { kennzeichen: "DW", stadt: "Dippoldiswalde", bundesland: "Sachsen" },
    { kennzeichen: "DZ", stadt: "Delitzsch", bundesland: "Sachsen" },
	{ kennzeichen: "E", stadt: "Essen", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "EA", stadt: "Eisenach", bundesland: "Thüringen" },
    { kennzeichen: "EB", stadt: "Eilenburg", bundesland: "Sachsen" },
    { kennzeichen: "EBE", stadt: "Ebersberg", bundesland: "Bayern" },
    { kennzeichen: "EBN", stadt: "Ebern", bundesland: "Bayern" },
    { kennzeichen: "EBS", stadt: "Ebermannstadt", bundesland: "Bayern" },
    { kennzeichen: "ECK", stadt: "Eckernförde", bundesland: "Schleswig-Holstein" },
    { kennzeichen: "ED", stadt: "Erding", bundesland: "Bayern" },
    { kennzeichen: "EE", stadt: "Elbe-Elster", bundesland: "Brandenburg" },
    { kennzeichen: "EF", stadt: "Erfurt", bundesland: "Thüringen" },
    { kennzeichen: "EG", stadt: "Eggenfelden", bundesland: "Bayern" },
    { kennzeichen: "EH", stadt: "Eisenhüttenstadt", bundesland: "Brandenburg" },
    { kennzeichen: "EHI", stadt: "Ehingen (Donau)", bundesland: "Baden-Württemberg" },
    { kennzeichen: "EI", stadt: "Eichstätt", bundesland: "Bayern" },
    { kennzeichen: "EIC", stadt: "Eichsfeld", bundesland: "Thüringen" },
    { kennzeichen: "EIH", stadt: "Eichstätt", bundesland: "Bayern" },
    { kennzeichen: "EIL", stadt: "Eisleben", bundesland: "Sachsen-Anhalt" },
    { kennzeichen: "EIN", stadt: "Einbeck", bundesland: "Niedersachsen" },
    { kennzeichen: "EIS", stadt: "Eisenberg", bundesland: "Thüringen" },
    { kennzeichen: "EL", stadt: "Emsland", bundesland: "Niedersachsen" },
    { kennzeichen: "EM", stadt: "Emmendingen", bundesland: "Baden-Württemberg" },
    { kennzeichen: "EMD", stadt: "Emden", bundesland: "Niedersachsen" },
    { kennzeichen: "EMS", stadt: "Rhein-Lahn-Kreis (Bad Ems)", bundesland: "Rheinland-Pfalz" },
    { kennzeichen: "EN", stadt: "Ennepe-Ruhr-Kreis", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "ER", stadt: "Erlangen", bundesland: "Bayern" },
    { kennzeichen: "ERB", stadt: "Odenwaldkreis (Erbach)", bundesland: "Hessen" },
    { kennzeichen: "ERH", stadt: "Erlangen-Höchstadt", bundesland: "Bayern" },
    { kennzeichen: "ERK", stadt: "Erkelenz", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "ERZ", stadt: "Erzgebirgskreis", bundesland: "Sachsen" },
    { kennzeichen: "ES", stadt: "Esslingen", bundesland: "Baden-Württemberg" },
    { kennzeichen: "ESB", stadt: "Eschenbach in der Oberpfalz", bundesland: "Bayern" },
    { kennzeichen: "ESA", stadt: "Eisenach", bundesland: "Thüringen" },
    { kennzeichen: "ESW", stadt: "Werra-Meißner-Kreis (Eschwege)", bundesland: "Hessen" },
    { kennzeichen: "EU", stadt: "Euskirchen", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "EUT", stadt: "Eutin", bundesland: "Schleswig-Holstein" },
    { kennzeichen: "EW", stadt: "Eberswalde", bundesland: "Brandenburg" },
    { kennzeichen: "F", stadt: "Frankfurt am Main", bundesland: "Hessen" },
    { kennzeichen: "FAL", stadt: "Fallingbostel", bundesland: "Niedersachsen" },
    { kennzeichen: "FB", stadt: "Wetteraukreis (Friedberg)", bundesland: "Hessen" },
    { kennzeichen: "FD", stadt: "Fulda", bundesland: "Hessen" },
    { kennzeichen: "FDB", stadt: "Friedberg", bundesland: "Bayern" },
    { kennzeichen: "FDS", stadt: "Freudenstadt", bundesland: "Baden-Württemberg" },
    { kennzeichen: "FEU", stadt: "Feuchtwangen", bundesland: "Bayern" },
    { kennzeichen: "FF", stadt: "Frankfurt (Oder)", bundesland: "Brandenburg" },
    { kennzeichen: "FFB", stadt: "Fürstenfeldbruck", bundesland: "Bayern" },
    { kennzeichen: "FG", stadt: "Mittelsachsen (Freiberg)", bundesland: "Sachsen" },
    { kennzeichen: "FH", stadt: "Main-Taunus-Kreis (Frankfurt/Main-Höchst)", bundesland: "Hessen" },
    { kennzeichen: "FI", stadt: "Finsterwalde", bundesland: "Brandenburg" },
    { kennzeichen: "FKB", stadt: "Frankenberg (Eder)", bundesland: "Hessen" },
    { kennzeichen: "FL", stadt: "Flensburg", bundesland: "Schleswig-Holstein" },
    { kennzeichen: "FLÖ", stadt: "Flöha", bundesland: "Sachsen" },
    { kennzeichen: "FN", stadt: "Bodenseekreis (Friedrichshafen)", bundesland: "Baden-Württemberg" },
    { kennzeichen: "FO", stadt: "Forchheim", bundesland: "Bayern" },
    { kennzeichen: "FOR", stadt: "Forst", bundesland: "Brandenburg" },
    { kennzeichen: "FR", stadt: "Freiburg im Breisgau", bundesland: "Baden-Württemberg" },
    { kennzeichen: "FRG", stadt: "Freyung-Grafenau", bundesland: "Bayern" },
    { kennzeichen: "FRI", stadt: "Friesland", bundesland: "Niedersachsen" },
    { kennzeichen: "FRW", stadt: "Bad Freienwalde", bundesland: "Brandenburg" },
    { kennzeichen: "FS", stadt: "Freising", bundesland: "Bayern" },
    { kennzeichen: "FT", stadt: "Frankenthal", bundesland: "Rheinland-Pfalz" },
    { kennzeichen: "FTL", stadt: "Freital", bundesland: "Sachsen" },
    { kennzeichen: "FÜ", stadt: "Fürth", bundesland: "Bayern" },
    { kennzeichen: "FÜS", stadt: "Füssen", bundesland: "Bayern" },
    { kennzeichen: "FW", stadt: "Fürstenwalde", bundesland: "Brandenburg" },
    { kennzeichen: "FZ", stadt: "Fritzlar-Homberg", bundesland: "Hessen" },
    { kennzeichen: "G", stadt: "Gera", bundesland: "Thüringen" },
    { kennzeichen: "GA", stadt: "Gardelegen", bundesland: "Sachsen-Anhalt" },
    { kennzeichen: "GAN", stadt: "Bad Gandersheim", bundesland: "Niedersachsen" },
    { kennzeichen: "GAP", stadt: "Garmisch-Partenkirchen", bundesland: "Bayern" },
    { kennzeichen: "GC", stadt: "Glauchau", bundesland: "Sachsen" },
    { kennzeichen: "GD", stadt: "Schwäbisch Gmünd", bundesland: "Baden-Württemberg" },
    { kennzeichen: "GDB", stadt: "Gadebusch", bundesland: "Mecklenburg-Vorpommern" },
    { kennzeichen: "GE", stadt: "Gelsenkirchen", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "GEL", stadt: "Geldern", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "GEM", stadt: "Gmünden am Main", bundesland: "Bayern" },
    { kennzeichen: "GEO", stadt: "Gerolzhofen", bundesland: "Bayern" },
    { kennzeichen: "GER", stadt: "Germersheim", bundesland: "Rheinland-Pfalz" },
    { kennzeichen: "GF", stadt: "Gifhorn", bundesland: "Niedersachsen" },
    { kennzeichen: "GG", stadt: "Groß-Gerau", bundesland: "Hessen" },
    { kennzeichen: "GHA", stadt: "Geithain", bundesland: "Sachsen" },
    { kennzeichen: "GHC", stadt: "Gräfenhainichen", bundesland: "Sachsen-Anhalt" },
    { kennzeichen: "GI", stadt: "Gießen", bundesland: "Hessen" },
    { kennzeichen: "GK", stadt: "Geilenkirchen-Heinsberg", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "GL", stadt: "Rheinisch-Bergischer Kreis (Bergisch Gladbach)", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "GLA", stadt: "Gladbeck", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "GM", stadt: "Oberbergischer Kreis (Gummersbach)", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "GMN", stadt: "Grimmen", bundesland: "Mecklenburg-Vorpommern" },
    { kennzeichen: "GN", stadt: "Gelnhausen", bundesland: "Hessen" },
    { kennzeichen: "GNT", stadt: "Genthin", bundesland: "Sachsen-Anhalt" },
    { kennzeichen: "GOA", stadt: "Sankt Goar", bundesland: "Rheinland-Pfalz" },
    { kennzeichen: "GÖ", stadt: "Göttingen", bundesland: "Niedersachsen" },
    { kennzeichen: "GOH", stadt: "St. Goarshausen", bundesland: "Rheinland-Pfalz" },
    { kennzeichen: "GP", stadt: "Göppingen", bundesland: "Baden-Württemberg" },
    { kennzeichen: "GR", stadt: "Görlitz", bundesland: "Sachsen" },
    { kennzeichen: "GRA", stadt: "Grafenau", bundesland: "Bayern" },
    { kennzeichen: "GRH", stadt: "Großenhain", bundesland: "Sachsen" },
    { kennzeichen: "GRI", stadt: "Bad Griesbach i. Rottal", bundesland: "Bayern" },
    { kennzeichen: "GRM", stadt: "Grimma", bundesland: "Sachsen" },
    { kennzeichen: "GRS", stadt: "Gransee", bundesland: "Brandenburg" },
    { kennzeichen: "GRZ", stadt: "Greiz", bundesland: "Thüringen" },
    { kennzeichen: "GS", stadt: "Goslar", bundesland: "Niedersachsen" },
    { kennzeichen: "GT", stadt: "Gütersloh", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "GTH", stadt: "Gotha", bundesland: "Thüringen" },
    { kennzeichen: "GUB", stadt: "Guben", bundesland: "Brandenburg" },
    { kennzeichen: "GÜ", stadt: "Güstrow", bundesland: "Mecklenburg-Vorpommern" },
    { kennzeichen: "GUN", stadt: "Gunzenhausen", bundesland: "Bayern" },
    { kennzeichen: "GV", stadt: "Grevenbroich", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "GVM", stadt: "Grevesmühlen", bundesland: "Mecklenburg-Vorpommern" },
    { kennzeichen: "GW", stadt: "Vorpommern-Greifswald", bundesland: "Mecklenburg-Vorpommern" },
    { kennzeichen: "GZ", stadt: "Günzburg", bundesland: "Bayern" },
    { kennzeichen: "H", stadt: "Hannover", bundesland: "Niedersachsen" },
    { kennzeichen: "HA", stadt: "Hagen", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "HAB", stadt: "Hammelburg", bundesland: "Bayern" },
    { kennzeichen: "HAL", stadt: "Halle", bundesland: "Sachsen-Anhalt" },
    { kennzeichen: "HAM", stadt: "Hamm", bundesland: "Nordrhein-Westfalen" },
    { kennzeichen: "HAM", stadt: "Hamm", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "HAS", stadt: "Haßberge (Haßfurt)", bundesland: "Bayern" },
	{ kennzeichen: "HB", stadt: "Hansestadt Bremen", bundesland: "Freie Hansestadt Bremen" },
	{ kennzeichen: "HBN", stadt: "Hildburghausen", bundesland: "Thüringen" },
	{ kennzeichen: "HBS", stadt: "Halberstadt", bundesland: "Sachsen-Anhalt" },
	{ kennzeichen: "HC", stadt: "Hainichen", bundesland: "Sachsen" },
	{ kennzeichen: "HCH", stadt: "Hechingen", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "HD", stadt: "Heidelberg", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "HDH", stadt: "Heidenheim (Brenz)", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "HDL", stadt: "Haldensleben", bundesland: "Sachsen-Anhalt" },
	{ kennzeichen: "HE", stadt: "Helmstedt", bundesland: "Niedersachsen" },
	{ kennzeichen: "HEB", stadt: "Hersbruck", bundesland: "Bayern" },
	{ kennzeichen: "HEF", stadt: "Hersfeld-Rotenburg", bundesland: "Hessen" },
	{ kennzeichen: "HEI", stadt: "Dithmarschen (Heide)", bundesland: "Schleswig-Holstein" },
	{ kennzeichen: "HER", stadt: "Herne", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "HET", stadt: "Hettstedt", bundesland: "Sachsen-Anhalt" },
	{ kennzeichen: "HF", stadt: "Herford", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "HG", stadt: "Hochtaunuskreis (Bad Homburg)", bundesland: "Hessen" },
	{ kennzeichen: "HGN", stadt: "Hagenow", bundesland: "Mecklenburg-Vorpommern" },
	{ kennzeichen: "HGW", stadt: "Hansestadt Greifswald", bundesland: "Mecklenburg-Vorpommern" },
	{ kennzeichen: "HH", stadt: "Hansestadt Hamburg", bundesland: "Freie und Hansestadt Hamburg" },
	{ kennzeichen: "HHM", stadt: "Hohenmölsen", bundesland: "Sachsen-Anhalt" },
	{ kennzeichen: "HI", stadt: "Hildesheim", bundesland: "Niedersachsen" },
	{ kennzeichen: "HIG", stadt: "Heiligenstadt", bundesland: "Thüringen" },
	{ kennzeichen: "HIP", stadt: "Hilpoltstein", bundesland: "Bayern" },
	{ kennzeichen: "HK", stadt: "Heidekreis", bundesland: "Niedersachsen" },
	{ kennzeichen: "HL", stadt: "Hansestadt Lübeck", bundesland: "Schleswig-Holstein" },
	{ kennzeichen: "HM", stadt: "Hameln-Pyrmont", bundesland: "Niedersachsen" },
	{ kennzeichen: "HMÜ", stadt: "Hann. Münden", bundesland: "Niedersachsen" },
	{ kennzeichen: "HN", stadt: "Heilbronn", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "HO", stadt: "Hof", bundesland: "Bayern" },
	{ kennzeichen: "HÖS", stadt: "Erlangen-Höchstadt", bundesland: "Bayern" },
	{ kennzeichen: "HOG", stadt: "Hofgeismar", bundesland: "Hessen" },
	{ kennzeichen: "HOH", stadt: "Hofheim in Unterfranken", bundesland: "Bayern" },
	{ kennzeichen: "HOL", stadt: "Holzminden", bundesland: "Niedersachsen" },
	{ kennzeichen: "HOM", stadt: "Saarpfalz-Kreis (Homburg)", bundesland: "Saarland" },
	{ kennzeichen: "HOR", stadt: "Freudenstadt (Horb am Neckar)", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "HOT", stadt: "Hohenstein-Ernstthal", bundesland: "Sachsen" },
	{ kennzeichen: "HP", stadt: "Bergstraße (Heppenheim)", bundesland: "Hessen" },
	{ kennzeichen: "HR", stadt: "Schwalm-Eder-Kreis (Homberg)", bundesland: "Hessen" },
	{ kennzeichen: "HRO", stadt: "Hansestadt Rostock", bundesland: "Mecklenburg-Vorpommern" },
	{ kennzeichen: "HS", stadt: "Heinsberg", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "HSK", stadt: "Hochsauerlandkreis", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "HST", stadt: "Hansestadt Stralsund", bundesland: "Mecklenburg-Vorpommern" },
	{ kennzeichen: "HU", stadt: "Hanau", bundesland: "Hessen" },
	{ kennzeichen: "HÜN", stadt: "Hünfeld", bundesland: "Hessen" },
	{ kennzeichen: "HUS", stadt: "Husum", bundesland: "Schleswig-Holstein" },
	{ kennzeichen: "HV", stadt: "Havelberg", bundesland: "Sachsen-Anhalt" },
	{ kennzeichen: "HVL", stadt: "Havelland (Rathenow)", bundesland: "Brandenburg" },
	{ kennzeichen: "HW", stadt: "Halle (Westfalen)", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "HWI", stadt: "Hansestadt Wismar", bundesland: "Mecklenburg-Vorpommern" },
	{ kennzeichen: "HX", stadt: "Höxter", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "HY", stadt: "Hoyerswerda", bundesland: "Sachsen" },
	{ kennzeichen: "HZ", stadt: "Landkreis Harz", bundesland: "Sachsen-Anhalt" },
	{ kennzeichen: "IGB", stadt: "St. Ingbert", bundesland: "Saarland" },
	{ kennzeichen: "IK", stadt: "Ilm-Kreis", bundesland: "Thüringen" },
	{ kennzeichen: "IL", stadt: "Ilmenau", bundesland: "Thüringen" },
	{ kennzeichen: "ILL", stadt: "Illertissen", bundesland: "Bayern" },
	{ kennzeichen: "IN", stadt: "Ingolstadt", bundesland: "Bayern" },
	{ kennzeichen: "IS", stadt: "Iserlohn", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "IZ", stadt: "Steinburg (Itzehoe)", bundesland: "Schleswig-Holstein" },
	{ kennzeichen: "J", stadt: "Jena", bundesland: "Thüringen" },
	{ kennzeichen: "JB", stadt: "Jüterbog", bundesland: "Brandenburg" },
	{ kennzeichen: "JE", stadt: "Jessen", bundesland: "Sachsen-Anhalt" },
	{ kennzeichen: "JEV", stadt: "Friesland (Jever)", bundesland: "Niedersachsen" },
	{ kennzeichen: "JL", stadt: "Jerichower Land", bundesland: "Sachsen-Anhalt" },
	{ kennzeichen: "JÜL", stadt: "Jülich", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "K", stadt: "Köln", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "KA", stadt: "Karlsruhe", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "KAR", stadt: "Main-Spessart (Karlstadt)", bundesland: "Bayern" },
	{ kennzeichen: "KB", stadt: "Waldeck-Frankenberg (Korbach)", bundesland: "Hessen" },
	{ kennzeichen: "KC", stadt: "Kronach", bundesland: "Bayern" },
	{ kennzeichen: "KE", stadt: "Kempten (Allgäu)", bundesland: "Bayern" },
	{ kennzeichen: "KEH", stadt: "Kelheim", bundesland: "Bayern" },
	{ kennzeichen: "KEL", stadt: "Kehl", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "KEM", stadt: "Kemnath", bundesland: "Bayern" },
	{ kennzeichen: "KF", stadt: "Kaufbeuren", bundesland: "Bayern" },
	{ kennzeichen: "KG", stadt: "Bad Kissingen", bundesland: "Bayern" },
	{ kennzeichen: "KH", stadt: "Bad Kreuznach", bundesland: "Rheinland-Pfalz" },
	{ kennzeichen: "KI", stadt: "Kiel", bundesland: "Schleswig-Holstein" },
	{ kennzeichen: "KIB", stadt: "Donnersbergkreis (Kirchheimbolanden)", bundesland: "Rheinland-Pfalz" },
	{ kennzeichen: "KK", stadt: "Kempen-Krefeld", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "KL", stadt: "Kaiserslautern", bundesland: "Rheinland-Pfalz" },
	{ kennzeichen: "KLE", stadt: "Kleve", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "KLZ", stadt: "Klötze", bundesland: "Sachsen-Anhalt" },
	{ kennzeichen: "KM", stadt: "Kamenz", bundesland: "Sachsen" },
	{ kennzeichen: "KN", stadt: "Konstanz", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "KO", stadt: "Koblenz", bundesland: "Rheinland-Pfalz" },
	{ kennzeichen: "KÖN", stadt: "Bad Königshofen i. Grabfeld", bundesland: "Bayern" },
	{ kennzeichen: "KÖT", stadt: "Köthen", bundesland: "Sachsen-Anhalt" },
	{ kennzeichen: "KÖZ", stadt: "Kötzting", bundesland: "Bayern" },
	{ kennzeichen: "KR", stadt: "Krefeld", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "KRU", stadt: "Krumbach", bundesland: "Bayern" },
	{ kennzeichen: "KS", stadt: "Kassel", bundesland: "Hessen" },
	{ kennzeichen: "KT", stadt: "Kitzingen", bundesland: "Bayern" },
	{ kennzeichen: "KU", stadt: "Kulmbach", bundesland: "Bayern" },
	{ kennzeichen: "KÜN", stadt: "Hohenlohekreis (Künzelsau)", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "KUS", stadt: "Kusel", bundesland: "Rheinland-Pfalz" },
	{ kennzeichen: "KW", stadt: "Königs Wusterhausen", bundesland: "Brandenburg" },
	{ kennzeichen: "KY", stadt: "Kyritz", bundesland: "Brandenburg" },
	{ kennzeichen: "KYF", stadt: "Kyffhäuserkreis", bundesland: "Thüringen" },
	{ kennzeichen: "L", stadt: "Leipzig", bundesland: "Sachsen" },
	{ kennzeichen: "LA", stadt: "Landshut", bundesland: "Bayern" },
	{ kennzeichen: "LAN", stadt: "Dingolfing-Landau", bundesland: "Bayern" },
	{ kennzeichen: "LAT", stadt: "Vogelsbergkreis (Lauterbach)", bundesland: "Hessen" },
	{ kennzeichen: "LAU", stadt: "Nürnberger Land (Lauf a.d. Pegnitz)", bundesland: "Bayern" },
	{ kennzeichen: "LB", stadt: "Ludwigsburg", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "LBS", stadt: "Lobenstein", bundesland: "Thüringen" },
	{ kennzeichen: "LBZ", stadt: "Lübz", bundesland: "Mecklenburg-Vorpommern" },
	{ kennzeichen: "LC", stadt: "Luckau", bundesland: "Brandenburg" },
	{ kennzeichen: "LD", stadt: "Landau in der Pfalz", bundesland: "Rheinland-Pfalz" },
	{ kennzeichen: "LDK", stadt: "Lahn-Dill-Kreis (Wetzlar)", bundesland: "Hessen" },
	{ kennzeichen: "LDS", stadt: "Dahme-Spreewald", bundesland: "Brandenburg" },
	{ kennzeichen: "LE", stadt: "Lemgo", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "LEO", stadt: "Leonberg (Württemberg)", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "LER", stadt: "Leer (Ostfriesland)", bundesland: "Niedersachsen" },
	{ kennzeichen: "LEV", stadt: "Leverkusen", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "LF", stadt: "Laufen", bundesland: "Bayern" },
	{ kennzeichen: "LG", stadt: "Lüneburg", bundesland: "Niedersachsen" },
	{ kennzeichen: "LH", stadt: "Lüdinghausen", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "LI", stadt: "Lindau (Bodensee)", bundesland: "Bayern" },
	{ kennzeichen: "LIB", stadt: "Bad Liebenwerda", bundesland: "Brandenburg" },
	{ kennzeichen: "LIF", stadt: "Lichtenfels", bundesland: "Bayern" },
	{ kennzeichen: "LIN", stadt: "Lingen (Ems)", bundesland: "Niedersachsen" },
	{ kennzeichen: "LIP", stadt: "Lippe (Detmold)", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "LK", stadt: "Lübbecke", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "LL", stadt: "Landsberg am Lech", bundesland: "Bayern" },
	{ kennzeichen: "LM", stadt: "Limburg-Weilburg", bundesland: "Hessen" },
	{ kennzeichen: "LN", stadt: "Lübben", bundesland: "Brandenburg" },
	{ kennzeichen: "LÖ", stadt: "Lörrach", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "LÖB", stadt: "Löbau", bundesland: "Sachsen" },
	{ kennzeichen: "LOH", stadt: "Lohr am Main", bundesland: "Bayern" },
	{ kennzeichen: "LOS", stadt: "Oder-Spree", bundesland: "Brandenburg" },
	{ kennzeichen: "LP", stadt: "Lippstadt", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "LR", stadt: "Lahr (Schwarzwald)", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "LRO", stadt: "Landkreis Rostock", bundesland: "Mecklenburg-Vorpommern" },
	{ kennzeichen: "LS", stadt: "Märkischer Kreis (Lüdenscheid)", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "LSZ", stadt: "Bad Langensalza", bundesland: "Thüringen" },
	{ kennzeichen: "LU", stadt: "Ludwigshafen am Rhein", bundesland: "Rheinland-Pfalz" },
	{ kennzeichen: "LÜD", stadt: "Lüdenscheid", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "LÜN", stadt: "Lünen", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "LUK", stadt: "Luckenwalde", bundesland: "Brandenburg" },
	{ kennzeichen: "LUP", stadt: "Ludwigslust-Parchim", bundesland: "Mecklenburg-Vorpommern" },
	{ kennzeichen: "LWL", stadt: "Ludwigslust", bundesland: "Mecklenburg-Vorpommern" },
	{ kennzeichen: "M", stadt: "München", bundesland: "Bayern" },
	{ kennzeichen: "MA", stadt: "Mannheim", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "MAB", stadt: "Marienberg", bundesland: "Sachsen" },
	{ kennzeichen: "MAI", stadt: "Mainburg", bundesland: "Bayern" },
	{ kennzeichen: "MAK", stadt: "Marktredwitz", bundesland: "Bayern" },
	{ kennzeichen: "MAL", stadt: "Mallersdorf", bundesland: "Bayern" },
	{ kennzeichen: "MAR", stadt: "Marktheidenfeld", bundesland: "Bayern" },
	{ kennzeichen: "MB", stadt: "Miesbach", bundesland: "Bayern" },
	{ kennzeichen: "MC", stadt: "Malchin", bundesland: "Mecklenburg-Vorpommern" },
	{ kennzeichen: "MD", stadt: "Magdeburg", bundesland: "Sachsen-Anhalt" },
	{ kennzeichen: "ME", stadt: "Mettmann", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "MED", stadt: "Süderdithmarschen (Meldorf/Holstein)", bundesland: "Schleswig-Holstein" },
	{ kennzeichen: "MEG", stadt: "Melsungen", bundesland: "Hessen" },
	{ kennzeichen: "MEI", stadt: "Meißen", bundesland: "Sachsen" },
	{ kennzeichen: "MEK", stadt: "Mittlerer Erzgebirgskreis", bundesland: "Sachsen" },
	{ kennzeichen: "MEL", stadt: "Melle", bundesland: "Niedersachsen" },
	{ kennzeichen: "MEP", stadt: "Meppen", bundesland: "Niedersachsen" },
	{ kennzeichen: "MER", stadt: "Merseburg", bundesland: "Sachsen-Anhalt" },
	{ kennzeichen: "MES", stadt: "Hochsauerlandkreis (Meschede)", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "MET", stadt: "Mellrichstadt", bundesland: "Bayern" },
	{ kennzeichen: "MG", stadt: "Mönchengladbach", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "MGH", stadt: "Bad Mergentheim", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "MGN", stadt: "Meiningen", bundesland: "Thüringen" },
	{ kennzeichen: "MH", stadt: "Mühlheim an der Ruhr", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "MHL", stadt: "Mühlhausen", bundesland: "Thüringen" },
	{ kennzeichen: "MI", stadt: "Minden-Lübbecke", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "MIL", stadt: "Miltenberg", bundesland: "Bayern" },
	{ kennzeichen: "MK", stadt: "Märkischer Kreis", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "MKK", stadt: "Main-Kinzig-Kreis", bundesland: "Hessen" },
	{ kennzeichen: "ML", stadt: "Mansfelder Land", bundesland: "Sachsen-Anhalt" },
	{ kennzeichen: "MM", stadt: "Memmingen", bundesland: "Bayern" },
	{ kennzeichen: "MN", stadt: "Unterallgäu (Mindelheim)", bundesland: "Bayern" },
	{ kennzeichen: "MO", stadt: "Moers", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "MOD", stadt: "Marktoberdorf", bundesland: "Bayern" },
	{ kennzeichen: "MOL", stadt: "Märkisch-Oderland", bundesland: "Brandenburg" },
	{ kennzeichen: "MON", stadt: "Monschau", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "MOS", stadt: "Neckar-Odenwald-Kreis (Mosbach)", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "MQ", stadt: "Merseburg-Querfurt", bundesland: "Sachsen-Anhalt" },
	{ kennzeichen: "MR", stadt: "Marburg-Biedenkopf", bundesland: "Hessen" },
	{ kennzeichen: "MS", stadt: "Münster", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "MSE", stadt: "Mecklenburgische Seenplatte", bundesland: "Mecklenburg-Vorpommern" },
	{ kennzeichen: "MSH", stadt: "Mansfeld-Südharz", bundesland: "Sachsen-Anhalt" },
	{ kennzeichen: "MSP", stadt: "Main-Spessart (Karlstadt)", bundesland: "Bayern" },
	{ kennzeichen: "MST", stadt: "Mecklenburg-Strelitz", bundesland: "Mecklenburg-Vorpommern" },
	{ kennzeichen: "MT", stadt: "Westerwald (Montabaur)", bundesland: "Rheinland-Pfalz" },
	{ kennzeichen: "MTK", stadt: "Main-Taunus-Kreis", bundesland: "Hessen" },
	{ kennzeichen: "MTL", stadt: "Muldentalkreis", bundesland: "Sachsen" },
	{ kennzeichen: "MUC", stadt: "München", bundesland: "Bayern" },
	{ kennzeichen: "MÜ", stadt: "Mühldorf am Inn", bundesland: "Bayern" },
	{ kennzeichen: "MÜB", stadt: "Münchberg", bundesland: "Bayern" },
	{ kennzeichen: "MÜL", stadt: "Müllheim", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "MÜN", stadt: "Münsingen (Württemberg)", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "MÜR", stadt: "Müritz", bundesland: "Mecklenburg-Vorpommern" },
	{ kennzeichen: "MW", stadt: "Mittweida", bundesland: "Sachsen" },
	{ kennzeichen: "MY", stadt: "Mayen", bundesland: "Rheinland-Pfalz" },
	{ kennzeichen: "MYK", stadt: "Mayen-Koblenz", bundesland: "Rheinland-Pfalz" },
	{ kennzeichen: "MZ", stadt: "Mainz, Mainz-Bingen", bundesland: "Rheinland-Pfalz" },
	{ kennzeichen: "MZG", stadt: "Merzig-Wadern", bundesland: "Saarland" },
	{ kennzeichen: "N", stadt: "Nürnberg", bundesland: "Bayern" },
	{ kennzeichen: "NAB", stadt: "Nabburg", bundesland: "Bayern" },
	{ kennzeichen: "NAI", stadt: "Naila", bundesland: "Bayern" },
	{ kennzeichen: "NAU", stadt: "Nauen", bundesland: "Brandenburg" },
	{ kennzeichen: "NB", stadt: "Neubrandenburg", bundesland: "Mecklenburg-Vorpommern" },
	{ kennzeichen: "ND", stadt: "Neuburg-Schrobenhausen", bundesland: "Bayern" },
	{ kennzeichen: "NDH", stadt: "Nordhausen", bundesland: "Thüringen" },
	{ kennzeichen: "NE", stadt: "Neuss", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "NEA", stadt: "Neustadt an der Aisch-Bad Windsheim", bundesland: "Bayern" },
	{ kennzeichen: "NEB", stadt: "Nebra", bundesland: "Sachsen-Anhalt" },
	{ kennzeichen: "NEC", stadt: "Neustadt b. Coburg", bundesland: "Bayern" },
	{ kennzeichen: "NEN", stadt: "Neunburg vorm Wald", bundesland: "Bayern" },
	{ kennzeichen: "NES", stadt: "Rhön-Grabfeld (Bad Neustadt a.d. Saale)", bundesland: "Bayern" },
	{ kennzeichen: "NEU", stadt: "Hochschwarzwald (Titisee-Neustadt)", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "NEW", stadt: "Neustadt an der Waldnaab", bundesland: "Bayern" },
	{ kennzeichen: "NF", stadt: "Nordfriesland (Husum)", bundesland: "Schleswig-Holstein" },
	{ kennzeichen: "NH", stadt: "Neuhaus", bundesland: "Thüringen" },
	{ kennzeichen: "NI", stadt: "Nienburg (Weser)", bundesland: "Niedersachsen" },
	{ kennzeichen: "NIB", stadt: "Süd Tondern (Niebüll)", bundesland: "Schleswig-Holstein" },
	{ kennzeichen: "NK", stadt: "Neunkirchen (Saar)", bundesland: "Saarland" },
	{ kennzeichen: "NM", stadt: "Neumarkt in der Oberpfalz", bundesland: "Bayern" },
	{ kennzeichen: "NMB", stadt: "Naumburg", bundesland: "Sachsen-Anhalt" },
	{ kennzeichen: "NMS", stadt: "Neumünster", bundesland: "Schleswig-Holstein" },
	{ kennzeichen: "NÖ", stadt: "Nördlingen", bundesland: "Bayern" },
	{ kennzeichen: "NOH", stadt: "Grafschaft Bentheim (Nordhorn)", bundesland: "Niedersachsen" },
	{ kennzeichen: "NOL", stadt: "Niederschlesischer Oberlausitzkreis", bundesland: "Sachsen" },
	{ kennzeichen: "NOM", stadt: "Northeim", bundesland: "Niedersachsen" },
	{ kennzeichen: "NOR", stadt: "Norden", bundesland: "Niedersachsen" },
	{ kennzeichen: "NP", stadt: "Neuruppin", bundesland: "Brandenburg" },
	{ kennzeichen: "NR", stadt: "Neuwied", bundesland: "Rheinland-Pfalz" },
	{ kennzeichen: "NRÜ", stadt: "Neustadt am Rübenberge", bundesland: "Niedersachsen" },
	{ kennzeichen: "NT", stadt: "Nürtingen", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "NU", stadt: "Neu-Ulm", bundesland: "Bayern" },
	{ kennzeichen: "NVP", stadt: "Nordvorpommern", bundesland: "Mecklenburg-Vorpommern" },
	{ kennzeichen: "NW", stadt: "Neustadt an der Weinstraße", bundesland: "Rheinland-Pfalz" },
	{ kennzeichen: "NWM", stadt: "Nordwestmecklenburg", bundesland: "Mecklenburg-Vorpommern" },
	{ kennzeichen: "NY", stadt: "Niesky", bundesland: "Sachsen" },
	{ kennzeichen: "NZ", stadt: "Neustrelitz", bundesland: "Mecklenburg-Vorpommern" },
	{ kennzeichen: "OA", stadt: "Oberallgäu", bundesland: "Bayern" },
	{ kennzeichen: "OAL", stadt: "Ostallgäu", bundesland: "Bayern" },
	{ kennzeichen: "OB", stadt: "Oberhausen", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "OBB", stadt: "Obernburg a. Main", bundesland: "Bayern" },
	{ kennzeichen: "OBG", stadt: "Osterburg", bundesland: "Sachsen-Anhalt" },
	{ kennzeichen: "OC", stadt: "Oschersleben", bundesland: "Sachsen-Anhalt" },
	{ kennzeichen: "OCH", stadt: "Ochsenfurt", bundesland: "Bayern" },
	{ kennzeichen: "OD", stadt: "Stormarn (Bad Oldesloe)", bundesland: "Schleswig-Holstein" },
	{ kennzeichen: "OE", stadt: "Olpe", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "ÖHR", stadt: "Öhringen", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "OF", stadt: "Offenbach am Main", bundesland: "Hessen" },
	{ kennzeichen: "OG", stadt: "Ortenaukreis (Offenburg)", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "OH", stadt: "Ostholstein", bundesland: "Schleswig-Holstein" },
	{ kennzeichen: "OHA", stadt: "Osterode am Harz", bundesland: "Niedersachsen" },
	{ kennzeichen: "OHV", stadt: "Oberhavel", bundesland: "Brandenburg" },
	{ kennzeichen: "OHZ", stadt: "Osterholz", bundesland: "Niedersachsen" },
	{ kennzeichen: "OK", stadt: "Ohrekreis", bundesland: "Sachsen-Anhalt" },
	{ kennzeichen: "OL", stadt: "Oldenburg", bundesland: "Niedersachsen" },
	{ kennzeichen: "OLD", stadt: "Oldenburg in Holstein", bundesland: "Schleswig-Holstein" },
	{ kennzeichen: "OP", stadt: "Rhein-Wupper-Kreis (Opladen)", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "OPR", stadt: "Ostprignitz-Ruppin", bundesland: "Brandenburg" },
	{ kennzeichen: "OR", stadt: "Oranienburg", bundesland: "Brandenburg" },
	{ kennzeichen: "OS", stadt: "Osnabrück", bundesland: "Niedersachsen" },
	{ kennzeichen: "OSL", stadt: "Oberspreewald-Lausitz", bundesland: "Brandenburg" },
	{ kennzeichen: "OTT", stadt: "Otterndorf", bundesland: "Niedersachsen" },
	{ kennzeichen: "OTW", stadt: "Ottweiler", bundesland: "Saarland" },
	{ kennzeichen: "OVI", stadt: "Oberviechtach", bundesland: "Bayern" },
	{ kennzeichen: "OVL", stadt: "Obervogtland", bundesland: "Sachsen" },
	{ kennzeichen: "OVP", stadt: "Ostvorpommern", bundesland: "Mecklenburg-Vorpommern" },
	{ kennzeichen: "OZ", stadt: "Oschatz", bundesland: "Sachsen" },
	{ kennzeichen: "P", stadt: "Potsdam", bundesland: "Brandenburg" },
	{ kennzeichen: "PA", stadt: "Passau", bundesland: "Bayern" },
	{ kennzeichen: "PAF", stadt: "Pfaffenhofen a.d. Ilm", bundesland: "Bayern" },
	{ kennzeichen: "PAN", stadt: "Rottal-Inn (Pfarrkirchen)", bundesland: "Bayern" },
	{ kennzeichen: "PAR", stadt: "Parsberg", bundesland: "Bayern" },
	{ kennzeichen: "PB", stadt: "Paderborn", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "PCH", stadt: "Parchim", bundesland: "Mecklenburg-Vorpommern" },
	{ kennzeichen: "PE", stadt: "Peine", bundesland: "Niedersachsen" },
	{ kennzeichen: "PEG", stadt: "Pegnitz", bundesland: "Bayern" },
	{ kennzeichen: "PER", stadt: "Perleberg", bundesland: "Brandenburg" },
	{ kennzeichen: "PF", stadt: "Pforzheim", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "PI", stadt: "Pinneberg", bundesland: "Schleswig-Holstein" },
	{ kennzeichen: "PIR", stadt: "Sächsische Schweiz-Osterzgebirge (Pirna)", bundesland: "Sachsen" },
	{ kennzeichen: "PK", stadt: "Pritzwalk", bundesland: "Brandenburg" },
	{ kennzeichen: "PL", stadt: "Plauen", bundesland: "Sachsen" },
	{ kennzeichen: "PLÖ", stadt: "Plön", bundesland: "Schleswig-Holstein" },
	{ kennzeichen: "PM", stadt: "Potsdam-Mittelmark", bundesland: "Brandenburg" },
	{ kennzeichen: "PN", stadt: "Pößneck", bundesland: "Thüringen" },
	{ kennzeichen: "PR", stadt: "Prignitz (Perleberg)", bundesland: "Brandenburg" },
	{ kennzeichen: "PRÜ", stadt: "Prüm", bundesland: "Rheinland-Pfalz" },
	{ kennzeichen: "PS", stadt: "Pirmasens", bundesland: "Rheinland-Pfalz" },
	{ kennzeichen: "PW", stadt: "Pasewalk", bundesland: "Mecklenburg-Vorpommern" },
	{ kennzeichen: "PZ", stadt: "Prenzlau", bundesland: "Brandenburg" },
	{ kennzeichen: "QFT", stadt: "Querfurt", bundesland: "Sachsen-Anhalt" },
	{ kennzeichen: "QLB", stadt: "Quedlinburg", bundesland: "Sachsen-Anhalt" },
	{ kennzeichen: "R", stadt: "Regensburg", bundesland: "Bayern" },
	{ kennzeichen: "RA", stadt: "Rastatt", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "RC", stadt: "Reichenbach", bundesland: "Sachsen" },
	{ kennzeichen: "RD", stadt: "Rendsburg-Eckernförde", bundesland: "Schleswig-Holstein" },
	{ kennzeichen: "RDG", stadt: "Ribnitz-Damgarten", bundesland: "Mecklenburg-Vorpommern" },
	{ kennzeichen: "RE", stadt: "Recklinghausen", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "REG", stadt: "Regen", bundesland: "Bayern" },
	{ kennzeichen: "REH", stadt: "Rehau", bundesland: "Bayern" },
	{ kennzeichen: "REI", stadt: "Bad Reichenhall", bundesland: "Bayern" },
	{ kennzeichen: "RG", stadt: "Riesa-Großenhain", bundesland: "Sachsen" },
	{ kennzeichen: "RH", stadt: "Roth", bundesland: "Bayern" },
	{ kennzeichen: "RI", stadt: "Rinteln", bundesland: "Niedersachsen" },
	{ kennzeichen: "RID", stadt: "Riedenburg", bundesland: "Bayern" },
	{ kennzeichen: "RIE", stadt: "Riesa", bundesland: "Sachsen" },
	{ kennzeichen: "RL", stadt: "Rochlitz", bundesland: "Sachsen" },
	{ kennzeichen: "RM", stadt: "Röbel (Müritz)", bundesland: "Mecklenburg-Vorpommern" },
	{ kennzeichen: "RN", stadt: "Rathenow", bundesland: "Brandenburg" },
	{ kennzeichen: "RO", stadt: "Rosenheim", bundesland: "Bayern" },
	{ kennzeichen: "ROD", stadt: "Roding", bundesland: "Bayern" },
	{ kennzeichen: "ROF", stadt: "Rotenburg an der Fulda", bundesland: "Hessen" },
	{ kennzeichen: "ROK", stadt: "Rockenhausen", bundesland: "Rheinland-Pfalz" },
	{ kennzeichen: "ROL", stadt: "Rottenburg a.d. Laaber", bundesland: "Bayern" },
	{ kennzeichen: "ROS", stadt: "Rostock", bundesland: "Mecklenburg-Vorpommern" },
	{ kennzeichen: "ROT", stadt: "Rothenburg o.d. Tauber", bundesland: "Bayern" },
	{ kennzeichen: "ROW", stadt: "Rotenburg (Wümme)", bundesland: "Niedersachsen" },
	{ kennzeichen: "RP", stadt: "Rhein-Pfalz-Kreis", bundesland: "Rheinland-Pfalz" },
	{ kennzeichen: "RS", stadt: "Remscheid", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "RSL", stadt: "Roßlau", bundesland: "Sachsen-Anhalt" },
	{ kennzeichen: "RT", stadt: "Reutlingen", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "RU", stadt: "Rudolstadt", bundesland: "Thüringen" },
	{ kennzeichen: "RÜD", stadt: "Rheingau-Taunus-Kreis", bundesland: "Hessen" },
	{ kennzeichen: "RÜG", stadt: "Rügen", bundesland: "Mecklenburg-Vorpommern" },
	{ kennzeichen: "RV", stadt: "Ravensburg", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "RW", stadt: "Rottweil", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "RY", stadt: "Rheydt", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "RZ", stadt: "Herzogtum Lauenburg (Ratzeburg)", bundesland: "Schleswig-Holstein" },
	{ kennzeichen: "S", stadt: "Stuttgart", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "SAB", stadt: "Saarburg", bundesland: "Rheinland-Pfalz" },
	{ kennzeichen: "SAD", stadt: "Schwandorf", bundesland: "Bayern" },
	{ kennzeichen: "SÄK", stadt: "Säckingen", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "SAN", stadt: "Stadtsteinach", bundesland: "Bayern" },
	{ kennzeichen: "SAW", stadt: "Altmarkkreis Salzwedel", bundesland: "Sachsen-Anhalt" },
	{ kennzeichen: "SB", stadt: "Saarbrücken", bundesland: "Saarland" },
	{ kennzeichen: "SBG", stadt: "Strasburg", bundesland: "Mecklenburg-Vorpommern" },
	{ kennzeichen: "SBK", stadt: "Schönebeck", bundesland: "Sachsen-Anhalt" },
	{ kennzeichen: "SC", stadt: "Schwabach", bundesland: "Bayern" },
	{ kennzeichen: "SCZ", stadt: "Schleiz", bundesland: "Thüringen" },
	{ kennzeichen: "SDH", stadt: "Sondershausen", bundesland: "Thüringen" },
	{ kennzeichen: "SDL", stadt: "Stendal", bundesland: "Sachsen-Anhalt" },
	{ kennzeichen: "SDT", stadt: "Schwedt (Oder)", bundesland: "Brandenburg" },
	{ kennzeichen: "SE", stadt: "Segeberg", bundesland: "Schleswig-Holstein" },
	{ kennzeichen: "SEB", stadt: "Sebnitz", bundesland: "Sachsen" },
	{ kennzeichen: "SEE", stadt: "Seelow", bundesland: "Brandenburg" },
	{ kennzeichen: "SEF", stadt: "Scheinfeld", bundesland: "Bayern" },
	{ kennzeichen: "SEL", stadt: "Selb", bundesland: "Bayern" },
	{ kennzeichen: "SF", stadt: "Sonthofen", bundesland: "Bayern" },
	{ kennzeichen: "SFA", stadt: "Soltau-Fallingbostel", bundesland: "Niedersachsen" },
	{ kennzeichen: "SFB", stadt: "Senftenberg", bundesland: "Brandenburg" },
	{ kennzeichen: "SFT", stadt: "Staßfurt", bundesland: "Sachsen-Anhalt" },
	{ kennzeichen: "SG", stadt: "Solingen", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "SGH", stadt: "Sangerhausen", bundesland: "Sachsen-Anhalt" },
	{ kennzeichen: "SHA", stadt: "Schwäbisch Hall", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "SHG", stadt: "Schaumburg", bundesland: "Niedersachsen" },
	{ kennzeichen: "SHK", stadt: "Saale-Holzland-Kreis", bundesland: "Thüringen" },
	{ kennzeichen: "SHL", stadt: "Suhl", bundesland: "Thüringen" },
	{ kennzeichen: "SI", stadt: "Siegen-Wittgenstein", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "SIG", stadt: "Sigmaringen", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "SIM", stadt: "Rhein-Hunsrück-Kreis (Simmern)", bundesland: "Rheinland-Pfalz" },
	{ kennzeichen: "SK", stadt: "Saalekreis", bundesland: "Sachsen-Anhalt" },
	{ kennzeichen: "SL", stadt: "Schleswig-Flensburg", bundesland: "Schleswig-Holstein" },
	{ kennzeichen: "SLE", stadt: "Schleiden", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "SLF", stadt: "Saalfeld-Rudolstadt", bundesland: "Thüringen" },
	{ kennzeichen: "SLG", stadt: "Saulgau (Württemberg)", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "SLK", stadt: "Salzlandkreis", bundesland: "Sachsen-Anhalt" },
	{ kennzeichen: "SLN", stadt: "Schmölln", bundesland: "Thüringen" },
	{ kennzeichen: "SLS", stadt: "Saarlouis", bundesland: "Saarland" },
	{ kennzeichen: "SLÜ", stadt: "Schlüchtern", bundesland: "Hessen" },
	{ kennzeichen: "SLZ", stadt: "Bad Salzungen", bundesland: "Thüringen" },
	{ kennzeichen: "SM", stadt: "Schmalkalden-Meiningen", bundesland: "Thüringen" },
	{ kennzeichen: "SMÜ", stadt: "Schwabmünchen", bundesland: "Bayern" },
	{ kennzeichen: "SN", stadt: "Schwerin", bundesland: "Mecklenburg-Vorpommern" },
	{ kennzeichen: "SNH", stadt: "Sinsheim", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "SO", stadt: "Soest", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "SOB", stadt: "Schrobenhausen", bundesland: "Bayern" },
	{ kennzeichen: "SOL", stadt: "Soltau", bundesland: "Niedersachsen" },
	{ kennzeichen: "SÖM", stadt: "Sömmerda", bundesland: "Thüringen" },
	{ kennzeichen: "SOG", stadt: "Schongau", bundesland: "Bayern" },
	{ kennzeichen: "SOK", stadt: "Saale-Orla-Kreis (Schleiz)", bundesland: "Thüringen" },
	{ kennzeichen: "SON", stadt: "Sonneberg", bundesland: "Thüringen" },
	{ kennzeichen: "SP", stadt: "Speyer", bundesland: "Rheinland-Pfalz" },
	{ kennzeichen: "SPB", stadt: "Spremberg", bundesland: "Brandenburg" },
	{ kennzeichen: "SPN", stadt: "Spree-Neiße", bundesland: "Brandenburg" },
	{ kennzeichen: "SPR", stadt: "Springe", bundesland: "Niedersachsen" },
	{ kennzeichen: "SR", stadt: "Straubing (-Bogen)", bundesland: "Bayern" },
	{ kennzeichen: "SRB", stadt: "Strausberg", bundesland: "Brandenburg" },
	{ kennzeichen: "SRO", stadt: "Stadtroda", bundesland: "Thüringen" },
	{ kennzeichen: "ST", stadt: "Steinfurt", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "STA", stadt: "Starnberg", bundesland: "Bayern" },
	{ kennzeichen: "STB", stadt: "Sternberg", bundesland: "Mecklenburg-Vorpommern" },
	{ kennzeichen: "STD", stadt: "Stade", bundesland: "Niedersachsen" },
	{ kennzeichen: "STE", stadt: "Staffelstein", bundesland: "Bayern" },
	{ kennzeichen: "STH", stadt: "Schaumburg-Lippe (Stadthagen)", bundesland: "Niedersachsen" },
	{ kennzeichen: "STL", stadt: "Stollberg", bundesland: "Sachsen" },
	{ kennzeichen: "STO", stadt: "Stockach (Sigmaringen)", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "SU", stadt: "Rhein-Sieg-Kreis (Siegburg)", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "SÜW", stadt: "Südliche Weinstraße", bundesland: "Rheinland-Pfalz" },
	{ kennzeichen: "SUL", stadt: "Sulzbach-Rosenberg", bundesland: "Bayern" },
	{ kennzeichen: "SW", stadt: "Schweinfurt", bundesland: "Bayern" },
	{ kennzeichen: "SWA", stadt: "Rheingau-Taunus-Kreis (Bad Schwalbach)", bundesland: "Hessen" },
	{ kennzeichen: "SY", stadt: "Grafschaft Hoya (Syke)", bundesland: "Niedersachsen" },
	{ kennzeichen: "SZ", stadt: "Salzgitter", bundesland: "Niedersachsen" },
	{ kennzeichen: "SZB", stadt: "Schwarzenberg", bundesland: "Sachsen" },
	{ kennzeichen: "TBB", stadt: "Main-Tauber-Kreis (Tauberbischofsheim)", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "TDO", stadt: "Torgau, Delitzsch, Oschatz (Nordsachsen)", bundesland: "Sachsen" },
	{ kennzeichen: "TE", stadt: "Tecklenburg", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "TET", stadt: "Teterow", bundesland: "Mecklenburg-Vorpommern" },
	{ kennzeichen: "TF", stadt: "Teltow-Fläming", bundesland: "Brandenburg" },
	{ kennzeichen: "TG", stadt: "Torgau", bundesland: "Sachsen" },
	{ kennzeichen: "TIR", stadt: "Tirschenreuth", bundesland: "Bayern" },
	{ kennzeichen: "TO", stadt: "Torgau-Oschatz", bundesland: "Sachsen" },
	{ kennzeichen: "TÖL", stadt: "Bad Tölz-Wolfratshausen", bundesland: "Bayern" },
	{ kennzeichen: "TÖN", stadt: "Eiderstedt (Tönning)", bundesland: "Schleswig-Holstein" },
	{ kennzeichen: "TP", stadt: "Templin", bundesland: "Brandenburg" },
	{ kennzeichen: "TR", stadt: "Trier", bundesland: "Rheinland-Pfalz" },
	{ kennzeichen: "TS", stadt: "Traunstein", bundesland: "Bayern" },
	{ kennzeichen: "TT", stadt: "Tettnang (Württemberg)", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "TÜ", stadt: "Tübingen", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "TUT", stadt: "Tuttlingen", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "UE", stadt: "Uelzen", bundesland: "Niedersachsen" },
	{ kennzeichen: "UEM", stadt: "Ueckermünde", bundesland: "Mecklenburg-Vorpommern" },
	{ kennzeichen: "ÜB", stadt: "Überlingen am Bodensee", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "UER", stadt: "Uecker-Randow", bundesland: "Mecklenburg-Vorpommern" },
	{ kennzeichen: "UFF", stadt: "Uffenheim", bundesland: "Bayern" },
	{ kennzeichen: "UH", stadt: "Unstrut-Hainich-Kreis", bundesland: "Thüringen" },
	{ kennzeichen: "UL", stadt: "Ulm", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "UM", stadt: "Uckermark", bundesland: "Brandenburg" },
	{ kennzeichen: "UN", stadt: "Unna", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "USI", stadt: "Usingen", bundesland: "Hessen" },
	{ kennzeichen: "V", stadt: "Vogtlandkreis", bundesland: "Sachsen" },
	{ kennzeichen: "VAI", stadt: "Vaihingen an der Enz", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "VB", stadt: "Vogelsbergkreis", bundesland: "Hessen" },
	{ kennzeichen: "VEC", stadt: "Vechta", bundesland: "Niedersachsen" },
	{ kennzeichen: "VER", stadt: "Verden", bundesland: "Niedersachsen" },
	{ kennzeichen: "VG", stadt: "Vorpommern-Greifswald", bundesland: "Mecklenburg-Vorpommern" },
	{ kennzeichen: "VIB", stadt: "Vilsbiburg", bundesland: "Bayern" },
	{ kennzeichen: "VIE", stadt: "Viersen", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "VIT", stadt: "Viechtach", bundesland: "Bayern" },
	{ kennzeichen: "VK", stadt: "Völklingen", bundesland: "Saarland" },
	{ kennzeichen: "VL", stadt: "Villingen (Schwarzwald)", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "VOF", stadt: "Vilshofen", bundesland: "Bayern" },
	{ kennzeichen: "VOH", stadt: "Vohenstrauß", bundesland: "Bayern" },
	{ kennzeichen: "VR", stadt: "Vorpommern-Rügen", bundesland: "Mecklenburg-Vorpommern" },
	{ kennzeichen: "VS", stadt: "Schwarzwald-Baar-Kreis (Villingen-Schwenningen)", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "W", stadt: "Wuppertal", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "WA", stadt: "Waldeck", bundesland: "Hessen" },
	{ kennzeichen: "WAF", stadt: "Warendorf", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "WAK", stadt: "Wartburgkreis", bundesland: "Thüringen" },
	{ kennzeichen: "WAN", stadt: "Wanne-Eickel", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "WAR", stadt: "Warburg", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "WAT", stadt: "Wattenscheid", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "WB", stadt: "Wittenberg", bundesland: "Sachsen-Anhalt" },
	{ kennzeichen: "WBG", stadt: "Wolfsburg", bundesland: "Niedersachsen" },
	{ kennzeichen: "WBS", stadt: "Worbis", bundesland: "Thüringen" },
	{ kennzeichen: "WD", stadt: "Wiedenbrück", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "WDA", stadt: "Werdau", bundesland: "Sachsen" },
	{ kennzeichen: "WE", stadt: "Weimar", bundesland: "Thüringen" },
	{ kennzeichen: "WEB", stadt: "Oberwesterwaldkreis (Westerburg)", bundesland: "Rheinland-Pfalz" },
	{ kennzeichen: "WEG", stadt: "Wegscheid", bundesland: "Bayern" },
	{ kennzeichen: "WEL", stadt: "Weilburg", bundesland: "Hessen" },
	{ kennzeichen: "WEM", stadt: "Wesermünde (Bremerhaven)", bundesland: "Niedersachsen" },
	{ kennzeichen: "WEN", stadt: "Weiden i. d. Oberpfalz", bundesland: "Bayern" },
	{ kennzeichen: "WER", stadt: "Wertingen", bundesland: "Bayern" },
	{ kennzeichen: "WES", stadt: "Wesel", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "WF", stadt: "Wolfenbüttel", bundesland: "Niedersachsen" },
	{ kennzeichen: "WG", stadt: "Wangen im Allgäu", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "WHV", stadt: "Wilhelmshaven", bundesland: "Niedersachsen" },
	{ kennzeichen: "WI", stadt: "Wiesbaden", bundesland: "Hessen" },
	{ kennzeichen: "WIL", stadt: "Wittlich", bundesland: "Rheinland-Pfalz" },
	{ kennzeichen: "WIS", stadt: "Wismar", bundesland: "Mecklenburg-Vorpommern" },
	{ kennzeichen: "WIT", stadt: "Witten", bundesland: "Nordrhein-Westfalen" },
	{ kennzeichen: "WIZ", stadt: "Witzenhausen", bundesland: "Hessen" },
	{ kennzeichen: "WK", stadt: "Wittstock", bundesland: "Brandenburg" },
	{ kennzeichen: "WL", stadt: "Harburg (Winsen/Luhe)", bundesland: "Niedersachsen" },
	{ kennzeichen: "WLG", stadt: "Wolgast", bundesland: "Mecklenburg-Vorpommern" },
	{ kennzeichen: "WM", stadt: "Weilheim-Schongau", bundesland: "Bayern" },
	{ kennzeichen: "WMS", stadt: "Wolmirstedt", bundesland: "Sachsen-Anhalt" },
	{ kennzeichen: "WN", stadt: "Rems-Murr-Kreis (Waiblingen)", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "WND", stadt: "St. Wendel", bundesland: "Saarland" },
	{ kennzeichen: "WO", stadt: "Worms", bundesland: "Rheinland-Pfalz" },
	{ kennzeichen: "WOB", stadt: "Wolfsburg", bundesland: "Niedersachsen" },
	{ kennzeichen: "WOH", stadt: "Wolfhagen", bundesland: "Hessen" },
	{ kennzeichen: "WOL", stadt: "Wolfach", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "WOR", stadt: "Wolfratshausen", bundesland: "Bayern" },
	{ kennzeichen: "WOS", stadt: "Wolfstein", bundesland: "Bayern" },
	{ kennzeichen: "WR", stadt: "Wernigerode", bundesland: "Sachsen-Anhalt" },
	{ kennzeichen: "WRN", stadt: "Waren", bundesland: "Mecklenburg-Vorpommern" },
	{ kennzeichen: "WS", stadt: "Wasserburg am Inn", bundesland: "Bayern" },
	{ kennzeichen: "WSF", stadt: "Weißenfels", bundesland: "Sachsen-Anhalt" },
	{ kennzeichen: "WST", stadt: "Ammerland (Westerstede)", bundesland: "Niedersachsen" },
	{ kennzeichen: "WSW", stadt: "Weißwasser", bundesland: "Sachsen" },
	{ kennzeichen: "WT", stadt: "Waldshut", bundesland: "Baden-Württemberg" },
	{ kennzeichen: "WTL", stadt: "Wittlage", bundesland: "Niedersachsen" },
	{ kennzeichen: "WTM", stadt: "Wittmund", bundesland: "Niedersachsen" },
	{ kennzeichen: "WÜ", stadt: "Würzburg", bundesland: "Bayern" },
	{ kennzeichen: "WÜM", stadt: "Waldmünchen", bundesland: "Bayern" },
	{ kennzeichen: "WUG", stadt: "Weißenburg-Gunzenhausen", bundesland: "Bayern" },
	{ kennzeichen: "WUN", stadt: "Wunsiedel", bundesland: "Bayern" },
	{ kennzeichen: "WUR", stadt: "Wurzen", bundesland: "Sachsen" },
	{ kennzeichen: "WW", stadt: "Westerwaldkreis", bundesland: "Rheinland-Pfalz" },
	{ kennzeichen: "WZ", stadt: "Wetzlar", bundesland: "Hessen" },
	{ kennzeichen: "WZL", stadt: "Wanzleben", bundesland: "Sachsen-Anhalt" },
	{ kennzeichen: "Z", stadt: "Zwickau", bundesland: "Sachsen" },
	{ kennzeichen: "ZE", stadt: "Zerbst", bundesland: "Sachsen-Anhalt" },
	{ kennzeichen: "ZEL", stadt: "Zell (Mosel)", bundesland: "Rheinland-Pfalz" },
	{ kennzeichen: "ZI", stadt: "Löbau-Zittau", bundesland: "Sachsen" },
	{ kennzeichen: "ZIG", stadt: "Ziegenhain (Schwalm-Eder-Kreis)", bundesland: "Hessen" },
	{ kennzeichen: "ZP", stadt: "Zschopau", bundesland: "Sachsen" },
	{ kennzeichen: "ZR", stadt: "Zeulenroda", bundesland: "Thüringen" },
	{ kennzeichen: "ZS", stadt: "Zossen", bundesland: "Brandenburg" },
	{ kennzeichen: "ZW", stadt: "Zweibrücken", bundesland: "Rheinland-Pfalz" },
	{ kennzeichen: "ZZ", stadt: "Zeitz", bundesland: "Sachsen-Anhalt" },
];